version: "3"
services:
  #ちなみにnodeはphp-fpm内にnodeを入れる
  php-fpm:
    container_name: vue_php
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    ports:
      - 9000:9000
    volumes:
      - .:/var/www/html/
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    networks:
      - vue

  nginx:
    container_name: vue_web
    image: nginx:alpine
    depends_on:
      - php-fpm
    ports:
      - 80:80
    volumes:
      - .:/var/www/html/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - vue  
  redis:
    container_name: vue_redis
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./redis/data:/data"
    networks:
      - vue
  redisinsight:
    container_name: vue_redis_gui  
    image: redislabs/redisinsight:latest
    ports:
      - 8001:8001
    volumes:
      - ./redis/insight:/db
    networks:
      - vue
networks:
  vue:
    driver: "bridge" 