version: "3"
services:
  #ちなみにnodeはphp-fpm内にnodeを入れる
  php-fpm:
    container_name: vue_php
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    ports:
      - 9000:9000
    volumes:
      - .:/var/www/html/
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
  nginx:
    container_name: vue_web
    image: nginx:alpine
    depends_on:
      - php-fpm
    ports:
      - 80:80
    volumes:
      - .:/var/www/html/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf